# Generated by Django 3.2.5 on 2021-07-06 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiusers', '0002_auto_20210705_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
    ]
