# Generated by Django 3.2.5 on 2021-07-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiusers', '0003_remove_user_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
